/* Chef Nova cooking education data lives separately from the main app logic. */
const cookingRules = [
  {
    id: 1,
    category: "Safety",
    title: "Wash hands before cooking",
    shortDescription: "Clean hands help keep germs out of food.",
    fullExplanation: "Your hands touch phones, doors, pets, backpacks, and many other surfaces. Washing before cooking removes germs that could move into food.",
    whyItMatters: "Clean hands lower the chance of spreading germs to food and to other people eating the meal.",
    steps: ["Wet your hands with warm running water.", "Add soap and scrub palms, backs of hands, between fingers, and under nails.", "Scrub for at least 20 seconds.", "Rinse well and dry with a clean towel."],
    commonMistakes: ["Rinsing without soap.", "Washing too quickly.", "Touching your phone right after washing."],
    example: "Before making a sandwich, wash your hands first, then start touching bread, cheese, and vegetables.",
    visual: "Hand washing"
  },
  {
    id: 2,
    category: "Safety",
    title: "Separate raw meat and vegetables",
    shortDescription: "Keep raw meat away from foods eaten fresh.",
    fullExplanation: "Raw meat can leave unsafe juices on boards, plates, knives, and hands. Those juices should not touch salad, fruit, cooked food, or anything eaten without more cooking.",
    whyItMatters: "Separating foods helps prevent cross-contamination, which is one of the most common kitchen safety problems.",
    steps: ["Use one board for raw meat and another for vegetables.", "Keep raw meat on a separate plate.", "Wash knives and boards after raw meat touches them.", "Wash your hands before touching other food."],
    commonMistakes: ["Cutting lettuce on a board that held raw chicken.", "Using the same tongs for raw and cooked meat.", "Letting meat juices drip in the fridge."],
    example: "Cut chicken on one board, put it in the pan, then use a clean board and knife for tomatoes.",
    visual: "Separate boards"
  },
  {
    id: 3,
    category: "Safety",
    title: "Cook chicken properly",
    shortDescription: "Chicken must be cooked all the way through.",
    fullExplanation: "Chicken can look cooked on the outside while still being unsafe inside. The thickest part needs enough heat to make it safe to eat.",
    whyItMatters: "Undercooked chicken can make people sick. Careful cooking protects everyone at the table.",
    steps: ["Cook chicken until no pink remains in the thickest part.", "Use a food thermometer if available.", "Check the thickest piece, not the smallest one.", "Let cooked chicken rest briefly before cutting."],
    commonMistakes: ["Only checking the outside color.", "Cooking pieces that are very different sizes together.", "Putting cooked chicken back on a plate that held raw chicken."],
    example: "For chicken strips, cut the thickest strip open and make sure it is fully cooked before serving.",
    visual: "Safe chicken cooking"
  },
  {
    id: 4,
    category: "Safety",
    title: "Do not leave stove unattended",
    shortDescription: "Stay near the stove when heat is on.",
    fullExplanation: "Food can burn, boil over, smoke, or catch fire faster than expected. A few minutes away can become a serious problem.",
    whyItMatters: "Watching the stove helps prevent burns, fires, ruined food, and kitchen damage.",
    steps: ["Stay in the kitchen while burners are on.", "Turn handles inward so pans are not bumped.", "Lower heat if food starts smoking.", "Turn off the stove as soon as cooking is done."],
    commonMistakes: ["Leaving to check a phone or game.", "Using high heat for everything.", "Forgetting a pan while multitasking."],
    example: "If pasta water is boiling, stay nearby so it does not bubble over onto the stove.",
    visual: "Stove watch"
  },
  {
    id: 5,
    category: "Hygiene",
    title: "Clean cutting boards after use",
    shortDescription: "Wash boards between different foods.",
    fullExplanation: "Cutting boards collect tiny pieces of food and liquid. Cleaning them prevents old food and germs from moving into the next ingredient.",
    whyItMatters: "A clean board keeps flavors fresh and helps prevent contamination.",
    steps: ["Scrape off food pieces.", "Wash with hot soapy water.", "Rinse well.", "Dry before putting it away or using it again."],
    commonMistakes: ["Only wiping with a dry towel.", "Using one board for the whole meal without washing.", "Putting a wet board away in a closed space."],
    example: "After slicing raw meat, wash the board before chopping cucumbers.",
    visual: "Clean board"
  },
  {
    id: 6,
    category: "Hygiene",
    title: "Tie back long hair",
    shortDescription: "Keep hair away from food and heat.",
    fullExplanation: "Loose hair can fall into food or get too close to flames, steam, mixers, or sticky ingredients.",
    whyItMatters: "Tying hair back keeps food cleaner and helps you move safely around the kitchen.",
    steps: ["Use a hair tie, clip, or headband.", "Secure loose front pieces.", "Check that hair stays back before cooking.", "Wash hands after touching hair."],
    commonMistakes: ["Tucking hair behind ears only.", "Fixing hair while cooking and not washing hands.", "Leaning over food with loose hair."],
    example: "Before mixing pancake batter, tie hair back so it does not fall near the bowl.",
    visual: "Hair tied back"
  },
  {
    id: 7,
    category: "Hygiene",
    title: "Use clean utensils",
    shortDescription: "Start with clean tools and switch when needed.",
    fullExplanation: "Spoons, knives, spatulas, and tongs can carry food residue or raw juices. Clean utensils keep the meal safer and better tasting.",
    whyItMatters: "Using clean tools prevents germs and unwanted flavors from spreading.",
    steps: ["Choose clean utensils before starting.", "Use separate tools for raw and cooked food.", "Set dirty utensils aside.", "Wash tools with hot soapy water."],
    commonMistakes: ["Using the same spoon to taste and stir.", "Using raw meat tongs on cooked food.", "Leaving utensils on dirty counters."],
    example: "Use one spatula for raw burger patties and a clean one after they are cooked.",
    visual: "Clean utensils"
  },
  {
    id: 8,
    category: "Hygiene",
    title: "Wipe counters before cooking",
    shortDescription: "Start with a clean workspace.",
    fullExplanation: "Counters can hold crumbs, spills, dust, and germs. Wiping them gives your ingredients a clean place to land.",
    whyItMatters: "A clean counter makes cooking safer, easier, and less stressful.",
    steps: ["Move clutter away.", "Wipe crumbs and spills.", "Use a clean cloth or paper towel with cleaner if needed.", "Let the area dry before setting food down."],
    commonMistakes: ["Cooking around clutter.", "Using a dirty sponge.", "Putting washed produce on an unclean counter."],
    example: "Before rolling dough, wipe and dry the counter so the dough stays clean.",
    visual: "Clean counter"
  },
  {
    id: 9,
    category: "Storage",
    title: "Store leftovers correctly",
    shortDescription: "Put leftovers away in sealed containers.",
    fullExplanation: "Leftovers should not sit out for too long. Sealed containers keep food fresher and stop spills or smells from spreading in the fridge.",
    whyItMatters: "Good storage helps food stay safe and reduces waste.",
    steps: ["Let very hot food cool briefly.", "Move food into a clean container.", "Seal the lid tightly.", "Put it in the fridge soon after the meal."],
    commonMistakes: ["Leaving food out for hours.", "Storing food in an open bowl.", "Mixing fresh food with old leftovers."],
    example: "After dinner, put extra curry in a container, close it, and refrigerate it.",
    visual: "Leftover container"
  },
  {
    id: 10,
    category: "Storage",
    title: "Check expiration dates",
    shortDescription: "Look at dates before using ingredients.",
    fullExplanation: "Expiration dates help you decide what to use first and what may no longer be safe or good quality.",
    whyItMatters: "Checking dates prevents spoiled food from ending up in a recipe.",
    steps: ["Find the date on the package.", "Check smell and appearance too.", "Use older safe ingredients first.", "Throw away food that seems spoiled."],
    commonMistakes: ["Ignoring dates on dairy or meat.", "Using food that smells strange.", "Buying new food while older food gets forgotten."],
    example: "Before pouring milk into pancake batter, check the date and smell it.",
    visual: "Date check"
  },
  {
    id: 11,
    category: "Storage",
    title: "Keep cold food cold",
    shortDescription: "Return cold foods to the fridge quickly.",
    fullExplanation: "Milk, meat, eggs, yogurt, and many leftovers need cold temperatures. Leaving them out too long can make them unsafe.",
    whyItMatters: "Cold storage slows down germ growth and keeps food fresher.",
    steps: ["Take cold food out only when needed.", "Use what you need.", "Close the package.", "Put it back in the fridge right away."],
    commonMistakes: ["Leaving milk out during the whole recipe.", "Letting meat sit on the counter too long.", "Forgetting leftovers after serving."],
    example: "After adding cheese to an omelette, put the cheese back in the fridge.",
    visual: "Cold storage"
  },
  {
    id: 12,
    category: "Storage",
    title: "Label opened food containers",
    shortDescription: "Write the date when food is opened.",
    fullExplanation: "Once a package is opened, it can spoil faster. A label helps you remember when you opened it.",
    whyItMatters: "Labels make it easier to use food while it is still fresh and safe.",
    steps: ["Write the food name if it is not clear.", "Add the date opened.", "Use tape or a label.", "Place older containers toward the front."],
    commonMistakes: ["Thinking you will remember the date.", "Leaving mystery containers in the fridge.", "Not sealing the container well."],
    example: "When opening a jar of sauce, label it with today's date before putting it back.",
    visual: "Food label"
  },
  {
    id: 13,
    category: "Cooking Tips",
    title: "Read the recipe before starting",
    shortDescription: "Know the steps before turning on heat.",
    fullExplanation: "Recipes often include timing, prep, and equipment details. Reading first helps you avoid surprises in the middle.",
    whyItMatters: "Planning ahead makes cooking calmer and helps prevent mistakes.",
    steps: ["Read the ingredient list.", "Read every step once.", "Check cooking times.", "Gather tools before starting."],
    commonMistakes: ["Starting before noticing a long step.", "Missing an ingredient halfway through.", "Turning on heat before prep is ready."],
    example: "Read the whole curry recipe before heating the pan so the onions, garlic, and spices are ready.",
    visual: "Recipe review"
  },
  {
    id: 14,
    category: "Cooking Tips",
    title: "Prepare ingredients first",
    shortDescription: "Chop and measure before cooking.",
    fullExplanation: "Many recipes move quickly once heat is on. Having ingredients ready keeps you from rushing or burning food.",
    whyItMatters: "Prepared ingredients help food cook evenly and reduce stress.",
    steps: ["Wash produce.", "Chop ingredients.", "Measure spices and liquids.", "Place everything near your cooking area."],
    commonMistakes: ["Chopping while food burns.", "Forgetting a key ingredient.", "Leaving packages open everywhere."],
    example: "Before stir-frying, slice beef, broccoli, and bell pepper first.",
    visual: "Ingredient prep"
  },
  {
    id: 15,
    category: "Cooking Tips",
    title: "Taste food while cooking",
    shortDescription: "Taste safely and adjust flavor.",
    fullExplanation: "Tasting helps you decide if food needs more salt, spice, acid, or sweetness. Only taste foods that are safe to taste.",
    whyItMatters: "Small adjustments while cooking make the final meal taste better.",
    steps: ["Use a clean spoon.", "Taste only cooked or safe foods.", "Adjust a little at a time.", "Taste again after stirring."],
    commonMistakes: ["Using the same spoon repeatedly.", "Adding too much seasoning at once.", "Tasting raw meat mixtures."],
    example: "Taste soup near the end and add a small pinch of salt if it tastes flat.",
    visual: "Taste and adjust"
  },
  {
    id: 16,
    category: "Cooking Tips",
    title: "Let hot food cool before storing",
    shortDescription: "Cool hot food briefly before sealing.",
    fullExplanation: "Very hot food can create steam inside containers. A short cooling time helps prevent extra moisture while still storing food safely.",
    whyItMatters: "Cooling correctly protects food texture and helps leftovers store better.",
    steps: ["Turn off the heat.", "Let food cool briefly.", "Move it into shallow containers if there is a lot.", "Refrigerate soon after it stops steaming heavily."],
    commonMistakes: ["Sealing very steamy food right away.", "Leaving food out for too long.", "Putting a huge deep pot directly in the fridge."],
    example: "Let a pot of soup stop steaming heavily, then store it in smaller containers.",
    visual: "Cooling food"
  }
];

window.cookingRules = cookingRules;
